apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob_every_15min
spec:
  schedule: "0,15,30,45 * * * *"
  # Minute, Hour, Day of Month, Month, Day of Week
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
