apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name: kubia
      livenessProbe:
        httpGet: # perform an HTTP GET
          path: / # the path to request in the HTTP request
          port: 8080 # the network port the probe should connect to
        initialDelaySeconds: 15
