apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcontroller
spec:
  replicas: 3 # desired number of pod instances
  selector:
    app: kubia # label to select (the pod selector determining what pods the RC is operating on)
    # not specifying the selector is an option, in that case, it will be configured automatically from the labels in the pod template: hence it is better not to specify it twice
  template: # pod template
    metadata:
      labels: # label associated with the pod so to be able to select it
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - containerPort: 8080

