apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
spec:
  selector:
    matchLabels:
      app: kubia
  replicas: 4
  template:
    metadata:
      name: myapp
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - name: http
              containerPort: 8080

